### ISSUE TITLE
Add support for hive-server

### ISSUE THREAD

**Issue by zhenik** [Skatteetaten/terraform-nomad-hive#7]
Hivemetastore is finished. 

- [X] [hivemeastore](https://github.com/fredrikhgrelland/docker-hive/blob/master/bin/hivemetastore)
- [ ] [hiveserver](https://github.com/fredrikhgrelland/docker-hive/blob/master/bin/hiveserver)

**Comment by zhenik** [comment]
## Offer
@fredrikhgrelland 
I would like to suggest make coupled-implementation for `hivemetastore` and `hiveserver`.

It means that the module will contain 1 nomad job with two tasks retrospectively. Deploy two pods with integration between. 

## Why
Conditional rendering (of nomad jobs) will slow down delivery progress.

Next releases we can focus on how to segregate hive running modes into one nomad_job with conditional rendering.

Take a look at branch [feature/add-server](https://github.com/fredrikhgrelland/terraform-nomad-hive/tree/feature/add-server)

**Comment by fredrikhgrelland** [comment]
This is fine for now. Future iteration might offer three posibilities in this module. server/metastore/combined

**Comment by claesgill** [comment]
@zhenik Is this something we need to consider implementing in the near future?

**Comment by fredrikhgrelland** [comment]
@claesgill No. I even think we should actively NOT consider this. Hive _metastore_ is a requisite as a catalog service for common "big data" management tools. hive is not and is deeply entrenched in Hadoop. Trying to implement a working hive server to process data will be time consuming and reap no rewards. I suggest closing this issue as won't-do

**Comment by claesgill** [comment]
> @claesgill No. I even think we should actively NOT consider this. Hive _metastore_ is a requisite as a catalog service for common "big data" management tools. hive is not and is deeply entrenched in Hadoop. Trying to implement a working hive server to process data will be time consuming and reap no rewards. I suggest closing this issue as won't-do

Ok, thanks's for the update. Closing.
