### ISSUE TITLE
The hive docker image is built even if `local_docker_image` is set to false

### ISSUE THREAD

**Issue by pdmthorsrud** [Skatteetaten/terraform-nomad-hive#70]
## Current behaviour
The hive docker image is built regardless of the value of `local_docker_image`. 

## Expected behaviour
Should not run [build-docker book](https://github.com/Skatteetaten/terraform-nomad-hive/blob/master/dev/ansible/05_build_docker_image.yml) if `local_docker_image=false`. This is simply to save time.

## How to reproduce?
Run `make dev` or `make up` with `local_docker_image=false`.

## Suggestion(s)/solution(s) [Optional]
Add a [check](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#id2) in the [ansible playbook](https://github.com/Skatteetaten/terraform-nomad-hive/blob/master/dev/ansible/05_build_docker_image.yml) that makes it only run if `local_docker_image=true`. 

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by zhenik** [comment]
This issue up in priority due to problem of low speed for downloading of binaries from apache archive https://github.com/Skatteetaten/terraform-nomad-hive/issues/75#issuecomment-815592083
