### ISSUE TITLE
Re-implement healthcheck

### ISSUE THREAD

**Issue by claesgill** [Skatteetaten/terraform-nomad-hive#78]
## Current behaviour
The [hive-minio-availability](https://github.com/Skatteetaten/terraform-nomad-hive/blob/master/conf/nomad/hive.hcl#L62-L78) healthcheck produces the error `403: ACL token not found`. Resulting in failing tests.

## Expected behaviour
All tests run green.

## How to reproduce?
- Uncomment test and create a draft PR to see failing messages.

*Note: Running locally works fine*

## Suggestion(s)/solution(s) [Optional]
- Remove `hive-minio-availability` duplicate
- Re-implement the original `hive-minio-availability` healthcheck

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by fredrikhgrelland** [comment]
Please note: Running two checks is a hack not to change tests checking the number of checks passing.

**Comment by claesgill** [comment]
> Please note: Running two checks is a hack not to change tests checking the number of checks passing.

Oh, that's right. I'll reformulate the issue.
